# Generated by Django 5.2 on 2025-08-19 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Número telefónico')),
                ('phone_number_2', models.CharField(max_length=10, null=True, verbose_name='Número telefónico 2')),
                ('picture', models.ImageField(upload_to='students', verbose_name='Imagen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
