# Generated by Django 5.2 on 2025-08-16 02:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('registration_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de inscripción')),
                ('tuition_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de colegiatura')),
                ('certification_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de certificación')),
                ('exam_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Examen')),
                ('opening_commission_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comisión por apertura')),
                ('closing_commission_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comisión por cierre')),
                ('new_opening_commission_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comisión por alcanzar la meta')),
                ('threshold_sales_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ventas para alcanzar nueva comisión')),
                ('commission_amount_general_public', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comisión por publico en general')),
                ('is_active', models.BooleanField(verbose_name='Activo')),
                ('is_general_public', models.BooleanField(verbose_name='Es público en general')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalities.category')),
            ],
            options={
                'verbose_name': 'Sub categoría',
                'verbose_name_plural': 'Sub categorías',
            },
        ),
    ]
