# Generated by Django 5.2 on 2025-08-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalities', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'unique': 'Ya existe una categoría con este nombre.'}, max_length=60, unique=True),
        ),
    ]
