# Generated by Django 5.2 on 2025-08-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('commission_general_public', models.BooleanField(verbose_name='Recibe comisión por público en general')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Número telefónico')),
                ('phone_number_2', models.CharField(max_length=10, null=True, verbose_name='Número telefónico 2')),
                ('picture', models.ImageField(upload_to='employees', verbose_name='Imagen')),
                ('reference', models.CharField(max_length=6, unique=True, verbose_name='Referencia')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
